import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Alert,
  ScrollView,
  StatusBar,
  Platform,
  Share,
  Linking,
  SafeAreaView,
} from 'react-native';
import { useAuth } from '../contexts/AuthContext';
import ApiService from '../services/api';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';

const IndividualStudentReportScreen = ({ route, navigation }) => {
  const { user } = useAuth();
  const { student, course, selectedIntake, selectedSection } = route.params;
  const [attendanceData, setAttendanceData] = useState(
    (student.attendance || []).sort((a, b) => new Date(b.date) - new Date(a.date))
  );
  const [loading, setLoading] = useState(false);

  const getStatusColor = (status) => {
    switch (status) {
      case 'present': return '#4caf50';
      case 'absent': return '#f44336';
      default: return '#666';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'present': return '✅';
      case 'absent': return '❌';
      default: return '❓';
    }
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      weekday: 'short',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  const generateReportText = () => {
    // Sort attendance data by date (newest first) for report
    const sortedAttendanceData = [...attendanceData].sort((a, b) => new Date(b.date) - new Date(a.date));
    
    let report = `STUDENT ATTENDANCE REPORT\n`;
    report += `=====================================\n\n`;
    report += `Student Name: ${student.studentName}\n`;
    report += `Student ID: ${student.studentCustomId || 'N/A'}\n`;
    report += `Course: ${course.courseName} (${course.courseCode})\n`;
    report += `Intake: ${selectedIntake}\n`;
    report += `Section: ${selectedSection}\n`;
    report += `Report Generated: ${new Date().toLocaleDateString()}\n\n`;
    
    report += `ATTENDANCE SUMMARY\n`;
    report += `------------------\n`;
    report += `Total Days: ${student.totalDays}\n`;
    report += `Present Days: ${student.presentDays}\n`;
    report += `Absent Days: ${student.absentDays}\n`;
    report += `Attendance Percentage: ${student.attendancePercentage}%\n\n`;
    
    if (sortedAttendanceData.length > 0) {
      report += `DAILY ATTENDANCE RECORDS (Most Recent First)\n`;
      report += `-------------------------------------------\n`;
      sortedAttendanceData.forEach((record, index) => {
        report += `${index + 1}. ${formatDate(record.date)} - ${record.status.toUpperCase()}\n`;
      });
    } else {
      report += `No attendance records found.\n`;
    }
    
    report += `\n=====================================\n`;
    report += `Generated by SDP Attendance System\n`;
    
    return report;
  };

  const generateHTMLReport = () => {
    // Sort attendance data by date (newest first) for PDF
    const sortedAttendanceData = [...attendanceData].sort((a, b) => new Date(b.date) - new Date(a.date));
    
    let html = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Student Attendance Report - ${student.studentName}</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; font-size: 12px; }
            .header { text-align: center; border-bottom: 2px solid #007bff; padding-bottom: 10px; margin-bottom: 20px; }
            .section { margin-bottom: 20px; page-break-inside: avoid; }
            .section-title { background-color: #f8f9fa; padding: 8px; font-weight: bold; border-left: 4px solid #007bff; font-size: 14px; }
            .info-row { margin: 6px 0; }
            .stats-grid { display: table; width: 100%; margin: 15px 0; }
            .stats-row { display: table-row; }
            .stat-box { display: table-cell; text-align: center; padding: 12px; border: 1px solid #ddd; width: 25%; }
            .stat-number { font-size: 18px; font-weight: bold; }
            .stat-label { font-size: 10px; color: #666; margin-top: 3px; }
            .attendance-table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 10px; }
            .attendance-table th, .attendance-table td { padding: 6px; text-align: left; border: 1px solid #ddd; }
            .attendance-table th { background-color: #f8f9fa; font-weight: bold; }
            .present { color: #4caf50; font-weight: bold; }
            .absent { color: #f44336; font-weight: bold; }
            .footer { text-align: center; margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; color: #666; font-size: 10px; }
            .page-break { page-break-before: always; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>STUDENT ATTENDANCE REPORT</h1>
        </div>
        
        <div class="section">
            <div class="section-title">Student Information</div>
            <div class="info-row"><strong>Student Name:</strong> ${student.studentName}</div>
            <div class="info-row"><strong>Student ID:</strong> ${student.studentCustomId || 'N/A'}</div>
            <div class="info-row"><strong>Course:</strong> ${course.courseName} (${course.courseCode})</div>
            <div class="info-row"><strong>Intake:</strong> ${selectedIntake}</div>
            <div class="info-row"><strong>Section:</strong> ${selectedSection}</div>
            <div class="info-row"><strong>Report Generated:</strong> ${new Date().toLocaleDateString()}</div>
        </div>
        
        <div class="section">
            <div class="section-title">Attendance Summary</div>
            <div class="stats-grid">
                <div class="stats-row">
                    <div class="stat-box">
                        <div class="stat-number">${student.totalDays}</div>
                        <div class="stat-label">Total Days</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-number" style="color: #4caf50;">${student.presentDays}</div>
                        <div class="stat-label">Present Days</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-number" style="color: #f44336;">${student.absentDays}</div>
                        <div class="stat-label">Absent Days</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-number" style="color: ${parseFloat(student.attendancePercentage) >= 75 ? '#4caf50' : '#f44336'};">${student.attendancePercentage}%</div>
                        <div class="stat-label">Attendance</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-number" style="color: #ff9800;">${student.attendanceMarks || 0}</div>
                        <div class="stat-label">Marks (out of 5)</div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <div class="section-title">Daily Attendance Records (Most Recent First)</div>
            ${sortedAttendanceData.length > 0 ? `
            <table class="attendance-table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    ${sortedAttendanceData.map(record => `
                        <tr>
                            <td>${formatDate(record.date)}</td>
                            <td class="${record.status}">${record.status.toUpperCase()}</td>
                        </tr>
                    `).join('')}
                </tbody>
            </table>
            ` : '<p>No attendance records found for this student.</p>'}
        </div>
        
        <div class="footer">
            <p>Generated by SDP Attendance System</p>
        </div>
    </body>
    </html>
    `;
    
    return html;
  };

  const handleDownload = async () => {
    try {
      setLoading(true);
      
      // Sort attendance data by date (newest first)
      const sortedAttendanceData = [...attendanceData].sort((a, b) => new Date(b.date) - new Date(a.date));
      
      // Create HTML content for PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Student Attendance Report</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 40px;
              padding: 20px;
              line-height: 1.6;
              color: #333;
              background-color: #ffffff;
            }
            .header {
              text-align: center;
              color: #007bff;
              border-bottom: 2px solid #007bff;
              padding-bottom: 15px;
              margin-bottom: 30px;
            }
            .section {
              margin: 25px 0;
              padding: 15px;
              background-color: #f8f9fa;
              border-radius: 8px;
              border-left: 4px solid #007bff;
            }
            .section-title {
              font-weight: bold;
              color: #333;
              margin-bottom: 15px;
              font-size: 16px;
              text-transform: uppercase;
              letter-spacing: 1px;
            }
            .info {
              margin: 8px 0;
              padding: 5px 0;
            }
            .table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 15px;
              font-size: 12px;
              background-color: #ffffff;
              border-radius: 8px;
              overflow: hidden;
              box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .table th, .table td {
              border: 1px solid #ddd;
              padding: 12px;
              text-align: left;
            }
            .table th {
              background-color: #007bff;
              color: white;
              font-weight: bold;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .table td {
              background-color: #ffffff;
            }
            .table tr:nth-child(even) td {
              background-color: #f8f9fa;
            }
            .present {
              color: #4caf50;
              font-weight: bold;
            }
            .absent {
              color: #f44336;
              font-weight: bold;
            }
            .footer {
              text-align: center;
              margin-top: 40px;
              color: #666;
              font-size: 12px;
              border-top: 2px solid #007bff;
              padding-top: 15px;
            }
            @media print {
              body { 
                margin: 40px; 
                padding: 20px; 
              }
              .header { page-break-after: avoid; }
              .section { page-break-inside: avoid; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>STUDENT ATTENDANCE REPORT</h1>
          </div>
          
          <div class="section">
            <div class="section-title">Student Information</div>
            <div class="info"><strong>Student Name:</strong> ${student.studentName}</div>
            <div class="info"><strong>Student ID:</strong> ${student.studentCustomId || 'N/A'}</div>
            <div class="info"><strong>Course:</strong> ${course.courseName} (${course.courseCode})</div>
            <div class="info"><strong>Intake:</strong> ${selectedIntake}</div>
            <div class="info"><strong>Section:</strong> ${selectedSection}</div>
            <div class="info"><strong>Report Generated:</strong> ${new Date().toLocaleDateString()}</div>
          </div>
          
          <div class="section">
            <div class="section-title">Attendance Summary</div>
            <div class="info"><strong>Total Days:</strong> ${student.totalDays}</div>
            <div class="info"><strong>Present Days:</strong> ${student.presentDays}</div>
            <div class="info"><strong>Absent Days:</strong> ${student.absentDays}</div>
            <div class="info"><strong>Attendance Percentage:</strong> ${student.attendancePercentage}%</div>
            <div class="info"><strong>Attendance Marks:</strong> ${student.attendanceMarks || 0} (out of 5)</div>
          </div>
          
          <div class="section">
            <div class="section-title">Daily Attendance Records (Most Recent First)</div>
            ${sortedAttendanceData.length > 0 ? `
              <table class="table">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  ${sortedAttendanceData.map(record => `
                    <tr>
                      <td>${formatDate(record.date)}</td>
                      <td class="${record.status}">${record.status.toUpperCase()}</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            ` : '<p>No attendance records found for this student.</p>'}
          </div>
          
          <div class="footer">
            <p>Generated by SDP Attendance System</p>
          </div>
        </body>
        </html>
      `;
      
      // Create filename
      const fileName = `${student.studentName.replace(/\s+/g, '_')}_Attendance_Report_${new Date().toISOString().split('T')[0]}.pdf`;
      
      // Generate PDF with expo-print and save directly to device
      const { uri } = await Print.printToFileAsync({
        html: htmlContent,
        base64: false,
      });
      
      // Save PDF directly to device downloads folder
      
      try {
        // Create downloads directory if it doesn't exist
        const downloadsDir = FileSystem.documentDirectory + 'Downloads/';
        const dirInfo = await FileSystem.getInfoAsync(downloadsDir);
        if (!dirInfo.exists) {
          await FileSystem.makeDirectoryAsync(downloadsDir, { intermediates: true });
        }
        
        // Copy PDF to downloads folder
        const downloadPath = downloadsDir + fileName;
        await FileSystem.copyAsync({
          from: uri,
          to: downloadPath
        });
        
        Alert.alert('Success', `PDF saved to Downloads folder: ${fileName}`);
        
      } catch (fileError) {
        console.log('Direct save failed, using share as fallback:', fileError);
        
        // Fallback to sharing if direct save fails
        const isAvailable = await Sharing.isAvailableAsync();
        if (isAvailable) {
          await Sharing.shareAsync(uri, {
            mimeType: 'application/pdf',
            dialogTitle: fileName,
          });
        } else {
          await Share.share({
            url: uri,
            title: fileName,
            type: 'application/pdf',
          });
        }
        
        Alert.alert('Success', `PDF shared: ${fileName}`);
      }
      
    } catch (error) {
      console.error('PDF generation error:', error);
      Alert.alert('Error', 'Failed to generate PDF report');
    } finally {
      setLoading(false);
    }
  };

  const renderAttendanceGrid = () => (
    <View style={styles.attendanceGrid}>
      <View style={styles.gridHeader}>
        <Text style={styles.gridHeaderText}>Date</Text>
        <Text style={styles.gridHeaderText}>Status</Text>
      </View>
      {attendanceData.length > 0 ? (
        attendanceData.map((record, index) => (
          <View key={index} style={styles.gridRow}>
            <Text style={styles.gridRowText}>{formatDate(record.date)}</Text>
            <Text style={[styles.gridRowText, { color: getStatusColor(record.status) }]}>
              {getStatusIcon(record.status)} {record.status}
            </Text>
          </View>
        ))
      ) : (
        <Text style={styles.noRecordsText}>No attendance records found for this student.</Text>
      )}
    </View>
  );

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#f8f9fa" />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
        >
          <Text style={styles.backButtonText}>‹ Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Student Report</Text>
        <TouchableOpacity
          style={[styles.downloadButton, loading && styles.downloadButtonDisabled]}
          onPress={handleDownload}
          disabled={loading}
        >
          <Text style={styles.downloadButtonText}>
            {loading ? '⏳' : '📄'}
          </Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Student Info Card */}
        <View style={styles.studentInfoCard}>
          <Text style={styles.studentName}>{student.studentName}</Text>
          <Text style={styles.studentId}>Student ID: {student.studentCustomId || 'N/A'}</Text>
          <Text style={styles.courseInfo}>{course.courseName} ({course.courseCode})</Text>
          <Text style={styles.classInfo}>
            Intake: {selectedIntake} | Section: {selectedSection}
          </Text>
        </View>

        {/* Summary Stats */}
        <View style={styles.summaryCard}>
          <Text style={styles.summaryTitle}>Attendance Summary</Text>
          <View style={styles.statsRow}>
            <View style={styles.statItem}>
              <Text style={styles.statNumber}>{student.totalDays}</Text>
              <Text style={styles.statLabel}>Total Days</Text>
            </View>
            <View style={styles.statItem}>
              <Text style={[styles.statNumber, { color: '#4caf50' }]}>
                {student.presentDays}
              </Text>
              <Text style={styles.statLabel}>Present</Text>
            </View>
            <View style={styles.statItem}>
              <Text style={[styles.statNumber, { color: '#f44336' }]}>
                {student.absentDays}
              </Text>
              <Text style={styles.statLabel}>Absent</Text>
            </View>
            <View style={styles.statItem}>
              <Text style={[
                styles.statNumber, 
                { color: parseFloat(student.attendancePercentage) >= 75 ? '#4caf50' : '#f44336' }
              ]}>
                {student.attendancePercentage}%
              </Text>
              <Text style={styles.statLabel}>Attendance</Text>
            </View>
          </View>
          <View style={styles.marksRow}>
            <View style={styles.marksItem}>
              <Text style={[styles.marksNumber, { color: '#ff9800' }]}>{student.attendanceMarks || 0}</Text>
              <Text style={styles.marksLabel}>Attendance Marks (out of 5)</Text>
            </View>
          </View>
        </View>

        {/* Daily Attendance Records */}
        <View style={styles.recordsCard}>
          <Text style={styles.recordsTitle}>Daily Attendance Records</Text>
          {renderAttendanceGrid()}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 20,
    paddingTop: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  backButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  backButtonText: {
    fontSize: 18,
    color: '#007bff',
    fontWeight: '600',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  downloadButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: '#007bff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#0056b3',
  },
  downloadButtonText: {
    fontSize: 18,
    color: 'white',
    fontWeight: '600',
  },
  downloadButtonDisabled: {
    opacity: 0.5,
  },
  content: {
    flex: 1,
    padding: 20,
    paddingTop: 30,
    paddingBottom: 120,
  },
  studentInfoCard: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  studentName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  studentId: {
    fontSize: 16,
    color: '#007bff',
    fontWeight: '600',
    marginBottom: 5,
  },
  courseInfo: {
    fontSize: 16,
    color: '#666',
    marginBottom: 5,
  },
  classInfo: {
    fontSize: 14,
    color: '#888',
  },
  summaryCard: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  statLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 5,
  },
  marksRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  marksItem: {
    alignItems: 'center',
    backgroundColor: '#fff3e0',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffcc02',
  },
  marksNumber: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  marksLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
    fontWeight: '600',
  },
  recordsCard: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  recordsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  attendanceGrid: {
    borderWidth: 1,
    borderColor: '#e9ecef',
    borderRadius: 8,
  },
  gridHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  gridHeaderText: {
    flex: 1,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#333',
    fontSize: 14,
  },
  gridRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f3f5',
  },
  gridRowText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    color: '#495057',
  },
  noRecordsText: {
    textAlign: 'center',
    padding: 20,
    color: '#666',
    fontSize: 14,
    fontStyle: 'italic',
  },
});

export default IndividualStudentReportScreen;
